sudoku

In [1]:
import numpy as np

In [2]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [3]:
np.sum(s)

np.int64(405)

In [8]:
# for first 3rows nd 3columns
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [9]:
# for second 3rows nd 3columns
s[0:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [10]:
# the printing all data into rows,columns  
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [11]:
# checking of each row,columns has the total 45 from 9
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


<!-- for checking of rows -->

In [4]:
b=np.sum(s,axis=1)
for i in b:
    if i !=45:
        print("sudko is not valid")
        break
else:
    print("rows are valid")

rows are valid


<!-- # for checking of the columns -->

In [5]:
d=np.sum(s,axis=0)
for i in d:
    if i !=45:
        print("sudko is not valid")
        break
else:
    print("columns are valid")

columns are valid


# Students marks

In [12]:
import numpy as np
# columns:[Age,maths marks,science marks]
data=np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [13]:
# get the shape of the matrix
data.shape

(5, 3)

In [15]:
# find the average number of the student
np.mean(data[:,0])

np.float64(18.4)

In [16]:
# Extract Math marks of all the students
data[0:5,1:2] 

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [17]:
# Find the highest science marks
np.max(data[:,2])

np.int64(95)

In [18]:
# Get details of the students who scored more than 90 in maths
data[data[:,1]>90]

array([[19, 92, 88]])

In [19]:
# Increase math marks of all students by 5
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [20]:
# find how many students are younger than 19
len(data[data[:,0]<19])

3

In [21]:
# calculate the average marks in each subject (columns-wise mean)
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [22]:
# Get data of student who scored at least 80 in both subject
data[(data[:,1]>=80)&(data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [23]:
# replace all science marks <75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])